� Make security scans

diff --git a/.github/workflows/stage-ecr-deploy.yml b/.github/workflows/stage-ecr-deploy.yml
--- a/.github/workflows/stage-ecr-deploy.yml
+++ b/.github/workflows/stage-ecr-deploy.yml
@@ -82,14 +82,18 @@ jobs:
             export ECR_REGISTRY="${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
 
             echo "📦 Installing AWS CLI..."
-            curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip -q awscliv2.zip
-            sudo ./aws/install || true
+            sudo ./aws/install
+            export PATH=$PATH:/usr/local/bin
+
+            echo "🔐 Setting AWS Credentials..."
+            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
+            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+            export AWS_REGION="${{ secrets.AWS_REGION }}"
 
             echo "🔐 Logging into ECR..."
-            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY || {
-              echo "❌ ECR login failed"; exit 1;
-            }
+            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY || { echo "❌ ECR login failed"; exit 1; }
 
             echo "📥 Pulling images..."
             docker pull $ECR_REGISTRY/inventoryapp-client-stage:$VERSION_TAG || { echo "❌ Failed to pull client image"; exit 1; }
@@ -108,9 +112,6 @@ jobs:
             echo "🌍 Exporting environment variables..."
             export DATABASE_URL="${{ secrets.DATABASE_URL }}"
             export NEXT_PUBLIC_API_BASE_URL="${{ secrets.NEXT_PUBLIC_API_BASE_URL }}"
-            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
-            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
-            export AWS_REGION="${{ secrets.AWS_REGION }}"
             export AWS_S3_BUCKET_NAME="${{ secrets.AWS_S3_BUCKET_NAME }}"
 
             echo "🚀 Starting new containers..."
